name: pyomo-egret-environment
channels:
  - conda-forge
dependencies:
  - numpy=1.16.4
  - scipy=1.3.0
  - matplotlib=3.1.1
  - pandas=0.25.0
  - ipopt
  - glpk
  - rise=5.5.1
  - pip=19.2.1
  - pip:
    - pyomo
